set -g default-terminal "screen-256color"
set -as terminal-features ",xterm-256color:RGB"

unbind C-b
set -g prefix C-a
bind C-a send-prefix

set -g mouse on

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

bind '|' split-window -h -c "#{pane_current_path}"
bind '-' split-window -v -c "#{pane_current_path}"

# 1. Configurações da Nova Versão do Catppuccin (Estilo Config 3)
set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_status_style "rounded"
set-option -g status-position top

# Status à direita
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_directory}"
set -ag status-right "#{E:@catppuccin_status_session}"

set -g @catppuccin_window_default_text " #W"
set -g @catppuccin_window_current_text " #W"
set -g @catppuccin_window_text " #W"

# 2. Lista de Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'catppuccin/tmux'

# 3. Inicializador do TPM
run '~/.config/tmux/plugins/tpm/tpm'

run '~/.config/tmux/plugins/tpm/tpm'
