# Suporte a cores de 24-bit (True Color)
set -g default-terminal "screen-256color"
set -as terminal-features ",xterm-256color:RGB"

# Prefixo: Troca Ctrl+b por Ctrl+a
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Atalho para recarregar as configurações facilmente com <prefix> + r
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Tmux recarregado!"

# Habilita suporte ao mouse
set -g mouse on

# Numeração de janelas e painéis começando em 1 (mais ergonômico no teclado)
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Divisão de painéis abrindo no mesmo diretório atual
bind '|' split-window -h -c "#{pane_current_path}"
bind '-' split-window -v -c "#{pane_current_path}"

# 1. Configurações da Versão Nova do Catppuccin
set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_status_style "rounded"
set-option -g status-position top

# Barra de status
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_directory}"
set -ag status-right "#{E:@catppuccin_status_session}"

set -g @catppuccin_window_default_text " #W"
set -g @catppuccin_window_current_text " #W"
set -g @catppuccin_window_text " #W"

# 2. Lista de Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'catppuccin/tmux'

# 3. Auto-instalação e Inicializador do TPM
if "test ! -d ~/.config/tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm && ~/.config/tmux/plugins/tpm/bin/install_plugins'"

run '~/.config/tmux/plugins/tpm/tpm'
