preload = /home/gabriel/Documentos/backgrounds/blade_runner.png

wallpaper {
    monitor = HDMI-A-1
    path = /home/gabriel/Documentos/backgrounds/blade_runner.png
    fit_mode = cover
}

splash = false
